const ActionTypes = {
    // Appearance
    CHANGE_ACCENT_COLOR: "CHANGE_ACCENT_COLOR",
    CHANGE_BACKGROUND_COLOR: "CHANGE_BACKGROUND_COLOR",
    CHANGE_CONTENT_REGION: "CHANGE_CONTENT_REGION",
    CHANGE_PRIMARY_COLOR: "CHANGE_PRIMARY_COLOR",
    // 
    CHANGE_RESTRICTED_MODE: "CHANGE_RESTRICTED_MODE",
}

export default ActionTypes;